### PR TITLE
Check for integer overflows in RawBmp::parse

### PR DESCRIPTION
**Pull request by rfuest**
Thank you for helping out with tinybmp development! Please:

- [ ] Check that you've added passing tests and documentation
- [ ] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, etc) if your changes affect the **public API**
- [ ] Run `rustfmt` on the project
- [ ] Run `just build` (Linux/macOS only) and make sure it passes. If you use Windows, check that CI passes once you've opened the PR.

## PR description

[add your PR description here]

### CODE REVIEW

**Comment by jamwaffles** [comment]
Hey @rfuest, is this ready for review or still more work to be done?

**Comment by rfuest** [comment]
I wanted to leave the PR open in case @symeonp finds more issues in #30. But we could also merge this first and open new PRs in case other issues are found.

**Comment by symeonp** [comment]
Hey Ralf/James,

So I can confirm that this PR does indeed fixes the reported issues. I've been fuzzing it for a few hours now and so far
no new issues have been identified. However my next step is to play a bit with structured-aware fuzzing.
If you want you can close and merge this PR and yep if I find a new one I'm happy to open a new issue if that's ok for you!

Thanks

**Comment by rfuest** [comment]
> Let's go this way (IMO)

OK. I've updated the PR a bit and added some tests. It's now ready to be reviewed.

**Review by jamwaffles — APPROVED** [review]
Looks good! Some nice tricks with ranges in there.

**Comment by jamwaffles** [comment]
Should we do a 0.4.0 breaking release once this is merged? There are some nice improvements which would be good to get into peoples' hands.

**Comment by rfuest** [comment]
> Should we do a 0.4.0 breaking release once this is merged? There are some nice improvements which would be good to get into peoples' hands.

Yes, I think the code is ready to be released. One thing I noticed, that might be a good idea to change before the release, is that the front page of the docs (aka the README) doesn't mention the pixel getters as a way to access the image data.

**Pull request merged**
