### PR TITLE
Fix incorrect color table entry calculation

### LINKED ISSUE #18: Color palette not parsed correctly for 1BPP images
- Version of tinybmp in use (if applicable): 0.3.1

## Description of the problem/feature request/other

tinybmp does not display correctly negative images of depth 1.  (I did not test other depths).
If you take an 1bpp image and negate it (for instance, with ImageMagick -negate command), the new image will appear identical to the original when displayed by tinybmp.  The problems seems to be in the parsing of the color table, as negating an image just "flips" the colors in the table, leaving the individual pixels unchanged.

## Test case 

1. Create two test images with ImageMagick
```
convert -size 200x200 canvas:black -type bilevel  images/black.bmp
convert -size 200x200 canvas:white -type bilevel  images/white.bmp
```
2. Modify the tinybmp example to display these images.  Below are the changes to show `white.bmp`
```
diff --git a/eg-0.7/examples/image-bmp.rs b/eg-0.7/examples/image-bmp.rs
index bef1103..f65941d 100644
--- a/eg-0.7/examples/image-bmp.rs
+++ b/eg-0.7/examples/image-bmp.rs
@@ -8,17 +8,17 @@
 //! The `graphics` feature of `tinybmp` needs to be enabled in `Cargo.toml` to use the `Bmp` object
 //! with embedded-graphics.
 
-use embedded_graphics::{image::Image, pixelcolor::Rgb565, prelude::*};
+use embedded_graphics::{image::Image, pixelcolor::BinaryColor, prelude::*};
 use embedded_graphics_simulator::{OutputSettingsBuilder, SimulatorDisplay, Window};
 use tinybmp::Bmp;
 
 fn main() -> Result<(), core::convert::Infallible> {
-    let mut display: SimulatorDisplay<Rgb565> = SimulatorDisplay::new(Size::new(128, 128));
+    let mut display: SimulatorDisplay<BinaryColor> = SimulatorDisplay::new(Size::new(128, 128));
 
     // Load the BMP image.
     // The color type must be specified explicitly to match the color format used by the image,
     // otherwise the compiler may infer an incorrect type.
-    let bmp: Bmp<Rgb565> = Bmp::from_slice(include_bytes!("./assets/rust-pride.bmp")).unwrap();
+    let bmp: Bmp<BinaryColor> = Bmp::from_slice(include_bytes!("./assets/white.bmp")).unwrap();
 
     // To draw the `bmp` object to the display it needs to be wrapped in an `Image` object to set
     // the position at which it should drawn. Here, the top left corner of the image is set to
```
3. Observe a black image instead of the expected white.
image
4. Compare the images and observe that they only differ in the color table (offset 0x7a in header)
image

### PR DESCRIPTION
**Pull request by jamwaffles**
Cc https://github.com/embedded-graphics/tinybmp/issues/18#issuecomment-1101600500

Closes #18

Silly mistake on my part 🤦 

I'll merge this fix into master, but to update 0.3.x I'll need to create a new branch from the `v0.3.2` tag with this PR cherry picked into it to release from. A bit of a mess but I can't think of a better way.

### CODE REVIEW

**Comment by jamwaffles** [comment]
P.s. thank you @rfuest for [finding the issue so quickly](https://github.com/embedded-graphics/tinybmp/issues/18#issuecomment-1101620159).

**Comment by rfuest** [comment]
The fix looks good. But I don't think we should add an image of unknown origin/license to the repo.

**Comment by jamwaffles** [comment]
Good point, I didn't consider that. My imagemagick-fu is terrible so I'm not sure how to go about making an image of the right bit depth. Are you any good with `convert`?

**Comment by rfuest** [comment]
> Are you any good with convert?

No, but I can use a hex editor :grin: [chessboard-8px-1bit-0colors.zip](https://github.com/embedded-graphics/tinybmp/files/8507611/chessboard-8px-1bit-0colors.zip)

**Comment by jamwaffles** [comment]
Ach, my web developer roots are showing through again. I've added your image, although I had to hex edit your hex edit; the original image has an alpha of `0`, not `255` as your image has so I changed it to make the test pass again. Thanks for the kick start though.

**Comment by rfuest** [comment]
IMO we should also add tests to `chessboard-8px-1bit.rs` to make sure the image can actually be drawn correctly.

**Comment by jamwaffles** [comment]
Test added, as well as a changelog entry

**Comment by jamwaffles** [comment]
Thanks. I'll do some branching trickery to get this commit released while we continue breaking `master` (in the good way of course).

**Comment by rfuest** [comment]
> (in the good way of course).

Let's hope so.

**Pull request merged**
